# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main, dev_tests, action_test ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda env create --file ./envs/rissmed.yaml
        export PATH="/usr/share/miniconda/bin:$PATH"
        source activate rissmed
        pip install flake8
        pip install pytest
    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"
        source activate rissmed
        # stop the build if there are Python syntax errors or undefined names
        flake8 ./RIssmed/ConstraintPLFold.py --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 ./RIssmed/ConstraintPLFold.py --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"
        source activate rissmed
        pytest

>>>>>>> rewrite-functions
